let sites = [
    { name: "Jack McDade", url: 'https://jackmcdade.com'},
    { name: "Paul Jarvis", url: 'https://pjrvs.com'},
    { name: "Mighty Fine Copy", url: 'https://www.mightyfinecopy.com/'},
    { name: "Luigi Battaglioli", url: 'https://theluigi.com'},
    { name: "Ross Wintle", url: 'https://rosswintle.uk/'},
    { name: "David A. Lindahl", url: 'https://davidalindahl.com'},
    { name: "Miguel Piedrafita", url: 'https://miguelpiedrafita.com'},
    { name: "Teevio", url: 'https://teev.io'},
    { name: "Matt Lantz", url: 'https://mattlantz.ca'},
    { name: "Jamie Howard", url: 'https://jamiehoward.co'},
    { name: "Jesse Leite", url: 'https://jesseleite.com'},
    { name: "David Llop", url: 'https://davidllop.com'},
    { name: "Aaron Francis", url: 'https://aaronfrancis.com/'},
    { name: "Colin Dismuke", url: 'https://www.colindismuke.com'},
]
